### PR TITLE
[RFC] Make history save/restore work with zsh

### PR DESCRIPTION
**Pull request by MoSal**
This patchset augments the feature to save/restore shell history. The bash-specific feature now works with zsh too.

I added the option `@resurrect-save-shell-history` and made `@resurrect-save-bash-history` an alias
to it for backwards compatibility.

### CODE REVIEW

**Comment by JohnLunzer** [comment]
I would love to use this plugin but can't give up zsh. Would love to see this merged.

**Comment by Kriechi** [comment]
How can we move this forward? Any required changes we could help with?

**Comment by cocreature** [comment]
Any chance of seeing this being merged? It looks like it doesn’t merge cleanly anymore. I’d be happy to help with that if that is all that is missing.

**Comment by rivanov2** [comment]
@bruno- I would love to use this plugin as well for `zsh`; Could someone take a look please?

**Comment by Erulisse** [comment]
I'll go ahead and bump this.

**Comment by naglalakk** [comment]
I'm going to bump this as well. I would absolutely love love love this

**Comment by vyzyv** [comment]
Bumping as well, is there any fork including this patch?

**Comment by bruno-** [comment]
Hey peeps, sorry for waiting so long. I skimmed this one and it looked good. Will review again tomorrow and merge if it's all good.

**Comment by bruno-** [comment]
@MoSal ,
this feature is now merged to `master`. There were some conflicts which I resolved locally. You're still the commit author.

**Comment by MoSal** [comment]
@bruno- 
Thank you for taking the time to do this.

**Pull request closed without merging**
